---
title: "E. coli Mice scRNAseq"
subtitle: "Recluster Cell Types"
author: "Kennedi Todd"
date: "05/13/2025"
output:
  html_document:
  code_folding: hide
theme: cerulean
toc: true
toc_float: true
editor_options: 
  chunk_output_type: inline
---
  
# Setup
## Set working directory
```{r working_directory}
knitr::opts_knit$set(root.dir = ".")
```

## Load libraries
```{r libraries, message=FALSE, warnings=FALSE}
# load libraries
library(cowplot)        # plot_grid()
library(dotenv)         # load_dot_env()
library(dplyr)          # left_join()
library(ggplot2)        # ggplot()
library(gridExtra)      # grid.arrange()
library(rtracklayer)    # import()
library(scCustomize)    # Merge_Seurat_List()
library(Seurat)         # Read10X_h5()
library(SeuratWrappers) # RunPrestoAll
library(stringr)        # str_match()
```

## Variables and functions
```{r set_variables_and_thresholds}
# source thresholds and output paths
source("../../refs/thresholds_and_outs.R")
out <- paste0(out, "pass1/recluster_astrocytes/")

# single cell functions
files <- list.files("../../functions", full.names = TRUE)
invisible(lapply(files, source))

# load the environment variables
load_dot_env(file = "../../refs/.env")
project_dir <- Sys.getenv("PROJECT_DIR")

# cell type of interest to subcluster
cell_types <- c("Astrocytes")
```

## Load data
```{r load_data}
mouse.annotated <- readRDS(
  file = paste0( "../../rObjects/seurat_obj_annotated_", filtering_method, "_pass1.rds")
)
```

## UMAP
```{r annotated_umap}
# set colors
cluster_colors <- c("firebrick1","orange2","gold","green","darkgreen",
                    "cyan","cornflowerblue","blue","pink","deeppink3",
                    "purple","#D2B48C","#8B4513","gray","#000000")

# annotated umap
DimPlot(mouse.annotated,
        cols = cluster_colors,
        shuffle = TRUE)
```

# Recluster
## Subset
```{r subset_seurat}
# subset on cell types of interest
sub <- subset(mouse.annotated, annotated_clusters %in% cell_types)

# check
DimPlot(sub, shuffle = TRUE)
```

## Recluster
```{r recluster}
# split
sub[["RNA"]] <- split(sub[["RNA"]], f = sub$sample)

# transform
options(future.globals.maxSize = 8000 * 1024^2)
sub <- SCTransform(sub, verbose = FALSE)

# PCA
sub <- RunPCA(object = sub, assay = "SCT")
DefaultAssay(sub) <- "SCT"

# re-join layers
sub[["RNA"]] <- JoinLayers(sub[["RNA"]])

# elbow plot
ElbowPlot(sub,
          ndims = 40,
          reduction = "pca") +
  geom_vline(xintercept = 30, linetype = "dashed", color = "red")

# run UMAP
sub <- RunUMAP(sub,
               dims = 1:30,
               reduction = "pca",
               n.components = 3)

# Determine the K-nearest neighbor graph
sub <- FindNeighbors(object = sub,
                     assay = "SCT",
                     reduction = "pca",
                     dims = 1:30)

# Determine the clusters for various resolutions
sub <- FindClusters(object = sub,
                    algorithm = 1,
                    resolution = seq(0.1, 0.5, by = 0.1))

# Set default assay and normalize for visualization
DefaultAssay(sub) <- "RNA"
sub <- NormalizeData(sub)
```

## Unannotated UMAP
```{r unannotated_umap}
sub$seurat_clusters <- sub$SCT_snn_res.0.5
Idents(sub) <- "seurat_clusters"

u1 <- DimPlot(sub, shuffle = TRUE, label = TRUE)
u1

u2 <- DimPlot(sub, shuffle = TRUE, dims = c(2,3))
u2
```

```{r}
pdf(paste0(out, "unannotated_umap.pdf"), width = 6, height = 4)
u1
dev.off()
```

# Annotation
## Canonical markers
```{r canonical_markers}
canonical_markers <- c(
  "Aldoc", "Aqp4", "Gja1", "Clu", "Apoe",             # Astrocytes
  "Aif1", "C1qa", "P2ry12", "Tmem119","Trem2","Mrc1", # Microglia
  "Ptprb", "Cldn5", "Flt1",                           # Endothelial
   "Ttr", "Folr1",                                    # Choroid
  "Col1a1", "Col1a2", "Dcn",                          # Fibroblast
  "Cfap44", "Spag16",                                 # Ependymal
  "Mog", "Opalin", "Mal", "Mag", "Mbp",               # Oligodendrocytes
  "Pdgfra", "Cspg4", "Olig1", "Olig2", "Tnr",         # OPCs
  "Syt1", "Snap25", "Gad1", "Meg3", "Igfbpl1","Sox4", # Neurons
  "Pdgfrb", "Rgs5", "Acta2", "Vtn",                   # Mural
  "Cd3e","Itgax","S100a9"                             # Immune (T, DC, neutrophil)
)

d <- DotPlot(sub,
              features = canonical_markers,
              cols = "RdYlBu",
              assay = "RNA") +
  coord_flip() +
  theme(axis.text.x = element_text(angle = 45, hjust = 1)) 
d
```

```{r}
pdf(paste0(out, "unannotated_markers.pdf"), width = 10, height = 10)
d
dev.off()
```

## Assign idetities
```{r}
new_cluster_names <- c(
  "0" = "Astrocytes",
  "1" = "Astrocytes",
  "2" = "Astrocytes",
  "3" = "Astrocytes",
  "4" = "Astrocytes",
  "5" = "Astrocytes",
  "6" = "Astrocytes",
  "7" = "Astrocytes",
  "8" = "Astrocytes",
  "9" = "Astrocytes",
  "10" = "Cluster 10"
)

sub <- RenameIdents(sub, new_cluster_names)
sub$annotated_clusters <- Idents(sub)
```

## Annotated UMAP
```{r}
u1 <- DimPlot(sub, 
              group.by = "annotated_clusters", 
              shuffle = TRUE)
u1

u2 <- DimPlot(sub, 
              dims = c(2,3),
              group.by = "annotated_clusters", 
              shuffle = TRUE)
u2
```

```{r}
pdf(paste0(out, "annotated_umap.pdf"), width = 6, height = 4)
u1
dev.off()
```

## Canonical markers
```{r}
d <- DotPlot(sub,
              features = canonical_markers,
              cols = "RdYlBu",
              assay = "RNA") +
  coord_flip() +
  theme(axis.text.x = element_text(angle = 45, hjust = 1)) 
d
```

```{r}
pdf(paste0(out, "annotated_markers.pdf"), width = 6, height = 10)
d
dev.off()
```

